export const ActionTypes = {
    //PLATFORM
    SET_PLATFORM : "SET_PLATFORM",
    SELECTED_PLATFORM : "SELECTED_PLATFORM",
    REMOVE_SELECTED_PLATFORM : "REMOVE_SELECTED_PLATFORM",

    //TOKEN
    SET_TOKEN:"SET_TOKEN",
    SELECTED_TOKEN:"SELECTED_TOKEN",
    REMOVE_SELECTED_TOKEN : "REMOVE_SELECTED_TOKEN",

}