export const ActionTypes = {
    //PLATFORM
    SET_PLATFORM : "SET_PLATFORM",
    SELECTED_PLATFORM : "SELECTED_PLATFORM",
    REMOVE_SELECTED_PLATFORM : "REMOVE_SELECTED_PLATFORM",

    //TOKEN
    SET_TOKEN:"SET_TOKEN",
    SELECTED_TOKEN:"SELECTED_TOKEN",
    REMOVE_SELECTED_TOKEN : "REMOVE_SELECTED_TOKEN",

    // Dark Mode
    SET_DARK:"SET_DARK",
    SELCTED_DARK:"SELECTED_DARK",

    // White Mode
    SET_LIGHT: "SET_LIGHT",
    SELCTED_LIGHT: "SELECTED_LIGHT",

    //UnderWrite
    SET_UNDERWRITE:" SET_UNDERWRITE",
    SELECTED_UNDERWRITE:" SELECTED_UNDERWRITE",

    //Activate Protocal
    SET_PROTCAL:"SET_PROTOCAL",
    SELECTED_PROTOCAL:"SELECTED_PROTOCAL"
}