export const ActionTypes = {
    //PLATFORM
    SET_PLATFORM : "SET_PLATFORM",
    SELECTED_PLATFORM : "SELECTED_PLATFORM",
    REMOVE_SELECTED_PLATFORM : "REMOVE_SELECTED_PLATFORM",

    //TOKEN
    SET_TOKEN:"SET_TOKEN",
    SELECTED_TOKEN:"SELECTED_TOKEN", 
     //TOKEN
    SET_cTOKEN:"SET_cTOKEN",
    SELECTED_cTOKEN:"SELECTED_cTOKEN",


    // Dark Mode
    SET_DARK:"SET_DARK",
    SELCTED_DARK:"SELECTED_DARK",

    // White Mode
    SET_LIGHT: "SET_LIGHT",
    SELCTED_LIGHT: "SELECTED_LIGHT",

    //UnderWrite
    SET_UNDERWRITE:" SET_UNDERWRITE",
    SELECTED_UNDERWRITE:" SELECTED_UNDERWRITE",

    //Activate Protocal
    SET_PROTCAL:"SET_PROTOCAL",
    SELECTED_PROTOCAL:"SELECTED_PROTOCAL",

    //Activated Protocol
    SET_PROTOCOL_ACTIVATED:"SET_PROTOCOL_ACTIVATED",
    SELCTED_PROTOCOL_ACTIVATED:"SELCTED_PROTOCOL_ACTIVATED",

    //Key
    SET_KEY:"SET_KEY",
    SELECTED_KEY:"SELECTED_KEY",

    // 
    SET_CONTRACT:"SET_CONTRACT",
    SELECTED_CONTRACT:"SELECTED_CONTRACT",

    // Dropdown
    SET_DROPDOWN:"SET_DROPDOWN",
    SELECTED_DROPDOWN:"SELECTED_DROPDOWN",

    //Activated Insurance
    SET_ACTIVATED_INSURANCE:"SET_ACTIVATED_INSURANCE",
    SELECTED_ACTIVATED_INSURANCE:"SELECTED_ACTIVATED_INSURANCE",

    //Insurance Type
    SET_INSURANCE_TYPE:"SET_INSURANCE_TYPE",
    SELECTED_INSURANCE_TYPE:"SELECTED_INSURANCE_TYPE",

    //Insurance Category
    SET_INSURANCE_CATEGORY: "SET_INSURANCE_CATEGORY",
    SELECTED_INSURANCE_CATEGORY: "SELECTED_INSURANCE_CATEGORY",

    //Insurance Category
    SET_INSURANCE_METHOD: "SET_INSURANCE_METHOD",
    SELECTED_INSURANCE_METHOD: "SELECTED_INSURANCE_METHOD",

    //Transaction Address
    SET_TRANSACTION_ADDRESS:"SET_TRANSACTION_ADDRESS",
    SELECTED_TRANSACTION_ADDRESS:"SELECTED_TRANSACTION_ADDRESS",

    //Current Network
    SET_CURRENT_NETWORK:"SET_CURRENT_NETWORK",
    SELECTED_CURRENT_NETWORK:"SELECTED_CURRENT_NETWORK",


    //SubCategory Key
    SET_SUBCATEGORY_KEY:"SET_SUBCATEGORY_KEY",
    SELECTED_SUBCATEGORY_KEY:"SELECTED_SUBCATEGORY_KEY"
}